### ISSUE TITLE
The peer-finder folder is lost

### ISSUE THREAD

**Issue by yangandiris** [smallc2009/nacos-peer-finder-plugin-arm64#1]
Hello, could you tell me where I can find this folder?
<img width="923" alt="image" src="https://user-images.githubusercontent.com/6008810/167542061-bf47d292-f01f-48a6-a338-b8390c8aab1d.png">

**Comment by smallc2009** [comment]
@yangandiris  peer-finder has been uploaded. 

actually, this file is from [kmodules/peer-finder project](https://github.com/kmodules/peer-finder)
